### ISSUE TITLE
Can we somehow combine node and clusterNode into one interface?

### ISSUE THREAD

**Issue by xhebox** [pingcap/tipocket#364]
## Feature Request

**Is your feature request related to a problem? Please describe:**

These two are highly similar. And I did not see the reason that it is not one interface.

https://github.com/pingcap/tipocket/blob/master/pkg/cluster/cluster.go#L50-L58

https://github.com/pingcap/tipocket/blob/master/pkg/cluster/cluster.go#L65-L72

If there is a real different between them, embedding one node in another would share most common logic.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**
a `map[string]interface{}` would handle the difference, too.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mahjonp** [comment]
The concept `Node` stands for a Pod managed by Statefulset on K8s which has stable network ids, so the count of Node should equal to the count of related pods(e.g. TiDB replicas + TiKV replicas + PD replicas + TiFlash replicas ...).

The `ClientNode` refers to the service on K8s. In current cases use it as the service endpoint since it has better HA than `Node`.

**Comment by mahjonp** [comment]
Perhaps we can use `Node` as the cluster endpoint(just like how Jepsen does), But I think using service as the cluster endpoint is more in line with the way TiDB cluster on K8s.

**Comment by xhebox** [comment]
What do you think about: add new switches for tidb-operator, which will expose PD and TiKV as services?

**Comment by mahjonp** [comment]
> What do you think about: add new switches for tidb-operator, which will expose PD and TiKV as services?

PD and TiKV are also exposed by headless services(https://docs.pingcap.com/tidb-in-kubernetes/stable/access-tidb#clusterip)
